superhero_project/superhero_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheros/', include('superheros.urls')),
    path('', RedirectView.as_view(url='/superheros/'))
]

superhero_project/superheros/urls.py
from django.urls import path
from . import views

app_name = 'superheros'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:hero_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('delete_hero/<int:hero_id>/', views.delete_hero, name='delete_hero'),
    path('update_hero/<int:hero_id>/', views.update_hero, name='update_hero')
]

superhero_project/superheros/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
    name = models.CharField (max_length=50)
    alter_ego = models.CharField (max_length=50)
    primary_ability = models.CharField (max_length=50)
    secondary_ability = models.CharField (max_length=50)
    catch_phrase = models.CharField (max_length=50)

    def __str__(self):
        return self.name

        

superhero_project/superheros/forms.py
from django import forms
from django.forms import ModelForm, fields, widgets
from .models import Superhero

class HeroForm(ModelForm):
    class Meta:
        model = Superhero
        fields = ('name', 'alter_ego', 'primary_ability', 'secondary_ability', 'catch_phrase')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'alter_ego':forms.TextInput(attrs={'class': 'form-control'}),
            'primary_ability':forms.TextInput(attrs={'class': 'form-control'}),
            'secondary_ability':forms.TextInput(attrs={'class': 'form-control'}),
            'catch_phrase':forms.TextInput(attrs={'class': 'form-control'}),
        }

superhero_project/superheros/views.py
from django import forms
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, redirect
from .models import Superhero
from .forms import HeroForm

# Create your views here.

def index(request):
    all_heros = Superhero.objects.all()
    context = {
        'all_heros' : all_heros
    }
    return render(request, 'superheros/index.html', context )

def detail(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'single_hero': single_hero
    }
    return render(request, 'superheros/detail.html', context)

def create(request):
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego =request.POST.get('alter_ego')
        primary = request.POST.get('primary')
        secondary = request.POST.get('secondary')
        catchphrase = request.POST.get('catchphrase')
        new_hero = Superhero(name=name, alter_ego=alter_ego, primary_ability=primary, secondary_ability=secondary, catch_phrase=catchphrase)
        new_hero.save()
        return HttpResponseRedirect(reverse('superheros:index'))

    else:
        return render(request, 'superheros/create.html')

def delete_hero(request, hero_id):
    deleted_hero=Superhero.objects.get(pk=hero_id)
    deleted_hero.delete()
    # why is delete not recognized in the intellitext? Save is recognized. It works though.
    return HttpResponseRedirect(reverse('superheros:index'))

def update_hero(request, hero_id):
    updated_hero=Superhero.objects.get(pk=hero_id)
    form = HeroForm(request.POST or None, instance = updated_hero) 
    if form.is_valid():
        form.save()
    context = {
        'form': form,
        'updated_hero': updated_hero
    }
    return render(request, 'superheros/update_hero.html', context)
    # return HttpResponseRedirect(reverse('superheros:index')), context

    # def update_hero(request, hero_id):
#     update_hero=Superhero.objects.get(pk=hero_id)
#     context = {
#         'update_hero': update_hero
      
#     }
#     return render(request, 'superheros/update_hero.html', context)

# def update_hero(request, hero_id):
#     update_hero=Superhero.objects.get(pk=hero_id)
#     if request.method == "POST":
#         name = request.POST.get('name')
#         alter_ego =request.POST.get('alter_ego')
#         primary = request.POST.get('primary')
#         secondary = request.POST.get('secondary')
#         catchphrase = request.POST.get('catchphrase')
#         new_hero = update_hero(name=name, alter_ego=alter_ego, primary_ability=primary, secondary_ability=secondary, catch_phrase=catchphrase)
#         new_hero.save()
#         return HttpResponseRedirect(reverse('superheros:index'))

# def update_hero(request, hero_id):
#     submitted = False
#     if request.method == "POST":
#         form = HeroForm(request.POST)
#         if form.is_valid():
#             form.save()
#             # return HttpResponseRedirect(reverse('superheros:index')), submitted = True
#             return HttpResponseRedirect(reverse('superheros:index'))
#     else:
#         form = HeroForm
#         if 'submitted' in request.GET:
#             submitted = True
#     context = {
#         'form': form,
#         'submitted': submitted
#     }
#     return render(request, 'superheros/update_hero.html', context)

# def update_hero(request, hero_id):
#     form = HeroForm(request.POST) 
#     context = {
#         'form': form,
#     }
#     return render(request, 'superheros/update_hero.html', context)

superhero_project/superheros/templates/superheros/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Hero</title>
</head>
<body>
    <form action = "{% url 'superheros:create'%}" method="post">
        {% csrf_token %}
        Name: <input type="text" name="name" id="name"><br />
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego"><br />
        Primary Ability: <input type="text" name="primary" id="primary"><br />
        Secondary Ability: <input type="text" name="secondary" id="secondary"><br />
        Catchphrase: <input type="text" name="catchphrase" id="catchphrase"><br />
        <input type="submit" value="Add!">

    </form>
    <br>
    <br>
    <a href="{% url 'superheros:index' %}">Home</a>
</body>
</html>

superhero_project/superheros/templates/superheros/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Hero</title>
</head>
<body>
    <h1>Delete Hero</h1>
    <ul> {% delete_hero.delete %}</ul>



</body>
</html>

superhero_project/superheros/templates/superheros/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hero Detail</title>
</head>
    <body>
        <h1>{{single_hero.name}} </h1>
        <ul>
            <li><h2> {{single_hero.alter_ego}} </h2></li>
            <li><h2> {{single_hero.primary_ability}} </h2></li>
            <li><h2> {{single_hero.secondary_ability}} </h2></li>
            <li><h2> {{single_hero.catch_phrase}} </h2></li>
        </ul>
        <br>
        <br>
        <a href="{% url 'superheros:index' %}">Home</a>
    </body>
</html>

superhero_project/superheros/templates/superheros/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
</head>
<body>
    <h1>List of Heros</h1>
    <ul>
        {% for hero in all_heros %}
        <li><h2> {{hero.name}} - <a href ="{% url 'superheros:detail' hero.id%}">Click for details</a> - <a href ="{% url 'superheros:delete_hero' hero.id%}">Click to delete hero</a> - <a href ="{% url 'superheros:update_hero' hero.id%}">Click to update hero</a></h2></li>
        {% endfor %}
    </ul>
    <a href="{% url 'superheros:create'%}">Add New Hero</a>
</body>
</html>

superhero_project/superheros/templates/superheros/update_hero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Hero</title>
</head>
<body>
    <h1> {{update_hero}} </h1>
      <form action="" method=POST>
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input type="submit" value="Update">
    </form>
    <br>
    <br>
    <a href="{% url 'superheros:index' %}">Home</a>
</body>
</html>